#ifndef __I_ECOMAXMIN_H__
#define __I_ECOMAXMIN_H__

#include "IEcoBase1.h"

/* Keep the original interface IID generated by Eco Wizard. */
#ifndef __IID_IEcoMaxMin
static const UGUID IID_IEcoMaxMin = {0x01, 0x10, {0x65, 0x47, 0x41, 0x8E, 0x79, 0x24, 0x43, 0x7D, 0x92, 0x16, 0xE5, 0x4B, 0x95, 0x2E, 0x05, 0x55}};
#endif

typedef struct IEcoMaxMin* IEcoMaxMinPtr_t;
typedef struct IEcoMaxMinVTbl {
    /* IEcoUnknown */
    int16_t (ECOCALLMETHOD *QueryInterface)(IEcoMaxMinPtr_t me, const UGUID* riid, voidptr_t* ppv);
    uint32_t (ECOCALLMETHOD *AddRef)(IEcoMaxMinPtr_t me);
    uint32_t (ECOCALLMETHOD *Release)(IEcoMaxMinPtr_t me);

    /* Five numeric types; no libc functions needed. */
    int (ECOCALLMETHOD *MaxInt)(IEcoMaxMinPtr_t me, int a, int b);
    int (ECOCALLMETHOD *MinInt)(IEcoMaxMinPtr_t me, int a, int b);
    long (ECOCALLMETHOD *MaxLong)(IEcoMaxMinPtr_t me, long a, long b);
    long (ECOCALLMETHOD *MinLong)(IEcoMaxMinPtr_t me, long a, long b);
    float (ECOCALLMETHOD *MaxFloat)(IEcoMaxMinPtr_t me, float a, float b);
    float (ECOCALLMETHOD *MinFloat)(IEcoMaxMinPtr_t me, float a, float b);
    double (ECOCALLMETHOD *MaxDouble)(IEcoMaxMinPtr_t me, double a, double b);
    double (ECOCALLMETHOD *MinDouble)(IEcoMaxMinPtr_t me, double a, double b);
    long double (ECOCALLMETHOD *MaxLongDouble)(IEcoMaxMinPtr_t me, long double a, long double b);
    long double (ECOCALLMETHOD *MinLongDouble)(IEcoMaxMinPtr_t me, long double a, long double b);
} IEcoMaxMinVTbl, *IEcoMaxMinVTblPtr_t;

interface IEcoMaxMin {
    struct IEcoMaxMinVTbl *pVTbl;
} IEcoMaxMin;

#endif
